-- Quick fix: Just disable RLS completely
-- Run this to get the app working immediately

ALTER TABLE parties DISABLE ROW LEVEL SECURITY;
ALTER TABLE players DISABLE ROW LEVEL SECURITY;
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE rounds DISABLE ROW LEVEL SECURITY;
ALTER TABLE party_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_answers DISABLE ROW LEVEL SECURITY;
ALTER TABLE questions DISABLE ROW LEVEL SECURITY;